"""Approved starter sources. Fallback excerpts are public-agency summaries, not model output."""

APPROVED_SOURCES = [
    {
        "title": "Manure Management Plans",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/environmental-protection/animal-feeding-operations/afo-confinements/manure-management-plans",
        "jurisdiction": "Iowa",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "Iowa DNR explains which confinement feeding operations must submit manure management plans, when original and annual plans are due, where copies must be maintained, and which manure application records must be retained. Producers with MMPs must use certified manure applicators. Manure application records are to be kept for five years and made available to DNR on request.",
    },
    {
        "title": "Animal Feeding Operation Forms",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/environmental-protection/animal-feeding-operations/afo-forms",
        "jurisdiction": "Iowa",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "forms index",
        "fallback_excerpt": "Iowa DNR's official forms index links manure management plan forms, annual update forms, manure application recordkeeping forms, construction and expansion forms, permit applications, fee forms, and spill reporting guidance for animal feeding operations.",
    },
    {
        "title": "Iowa Code Chapter 459, Animal Agriculture Compliance Act",
        "agency": "Iowa Legislature",
        "url": "https://www.legis.iowa.gov/docs/code/459.pdf",
        "jurisdiction": "Iowa",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "statute",
        "publication_date": "2026-01-01",
        "manual_path": "corpus/manual/459.pdf",
        "fallback_excerpt": "Iowa Code chapter 459 is the Animal Agriculture Compliance Act. Section 459.303 requires a construction permit before building or expanding a confinement feeding operation structure when the completed operation will have at least 1,000 animal units or when the project uses an unformed manure storage structure. Section 459.312 requires a manure management plan to calculate the land needed for manure application using crop nitrogen needs and a phosphorus index. The operation's capacity, storage type, site, and related nearby operations determine which requirements apply.",
    },
    {
        "title": "AFO Confinements",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/environmental-protection/animal-feeding-operations/afo-confinements",
        "jurisdiction": "Iowa",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "Iowa DNR groups confinement feeding operations by animal unit capacity and manure storage type. A construction permit is required before building, modifying, or expanding an operation with formed manure storage when final capacity is 1,000 animal units or more, and for unformed manure storage regardless of size. Operations over 500 but under 1,000 animal units using formed storage do not need a construction permit, but must meet pre-construction and design requirements and have an approved manure management plan. Operations of 500 animal units or less using formed storage do not need a construction permit or MMP, but separation-distance and other rules still apply.",
    },
    {
        "title": "AFO Construction Permits",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/environmental-protection/animal-feeding-operations/afo-construction-permits",
        "jurisdiction": "Iowa",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "Iowa confinement feeding operations that plan to build, modify, or expand must determine the proposed animal unit capacity and manure storage type before construction. DNR advises doing this at least 120 days before construction. Every site must meet applicable separation distances and be checked for floodplain, karst, sinkhole, well, wetland, water-source, residence, business, school, church, public-use, and road constraints. Nearby commonly owned or managed operations may have to be combined when calculating capacity.",
    },
    {
        "title": "AFO Pre-Construction Requirements",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/environmental-protection/animal-feeding-operations/afo-construction-permits/afo-pre-construction-requirements",
        "jurisdiction": "Iowa",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "For a permitted confinement project, Iowa DNR requires a construction permit and manure management plan and says the owner must apply at least 60 days before construction begins. The application package may require construction forms, separation-distance documentation, design plans or engineering certification, a Master Matrix, stormwater planning, and floodplain or karst review. Projects over 500 but under 1,000 animal units using formed storage and small operations using formed storage can be non-permitted, but still have specified pre-construction, siting, design, and documentation requirements.",
    },
    {
        "title": "AFO Manure Application",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/environmental-protection/animal-feeding-operations/afo-manure-application",
        "jurisdiction": "Iowa",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "All manure applicators in Iowa must land apply manure without causing surface-water or groundwater pollution and must observe applicable separation distances. A producer applying manure from a confinement feeding operation with more than 500 animal units must be certified or use a certified commercial manure applicator. The DNR provides manure application recordkeeping form 542-8002. Certification is generally not required for a producer applying manure from a small operation of 500 animal units or less or from an open feedlot, but the land-application rules still apply.",
    },
    {
        "title": "Separation Distances for Land Application of Manure",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/Portals/idnr/uploads/afo/fs_sepdstb4.pdf",
        "jurisdiction": "Iowa",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official fact sheet",
        "publication_date": "2023-08-01",
        "manual_path": "corpus/manual/dnr-separation-distances.pdf",
        "fallback_excerpt": "Iowa DNR's land-application fact sheet explains that required separation distances vary by manure type, source, protected area, and application method. Injection or prompt incorporation can change some distances. Protected areas include residences, schools, businesses, churches, public-use areas, wells, sinkholes, water sources, designated wetlands, high-quality water resources, and agricultural drainage wells. Producers must check the applicable table before selecting fields and application methods.",
    },
    {
        "title": "Iowa Administrative Code Chapter 65, Animal Feeding Operations",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/media/2997/download?inline=",
        "jurisdiction": "Iowa",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "administrative rule",
        "publication_date": "2024-05-15",
        "fallback_excerpt": "Iowa Administrative Code chapter 65 contains detailed animal feeding operation rules for construction, separation distances, manure storage, manure management plans, land application, records, releases, and NPDES requirements. Records required by a manure management plan generally include actual manure application data and changes to the plan and must be retained for the period specified by the rule. The precise requirement depends on operation type, size, permit status, and the specific activity.",
    },
    {
        "title": "Spill Reporting Guidance for Animal Feeding Operations",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/media/2995/download?inline=",
        "previous_urls": ["https://www.iowadnr.gov/Portals/idnr/uploads/afo/afo-files/reporting-guidance.pdf"],
        "jurisdiction": "Iowa",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official guidance",
        "publication_date": "2024-09-01",
        "manual_path": "corpus/manual/dnr-spill-reporting.pdf",
        "fallback_excerpt": "Iowa DNR says manure releases and hazardous-substance releases must be reported to the DNR 24-hour spill line at 515-725-8694 and to local police or the county sheriff. A release must be reported within six hours after it occurred or was discovered. Reportable manure releases include actual, imminent, or probable discharges to surface water, groundwater, drainage tile or intakes, or designated areas during storage, handling, transportation, or land application. If uncertain, report and let DNR determine applicability.",
    },
    {
        "title": "Manure Management Plan Forms for Confinement Feeding Operations",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/media/5712/download?inline=",
        "previous_urls": ["https://www.iowadnr.gov/Portals/idnr/uploads/forms/5424000.pdf"],
        "jurisdiction": "Iowa",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official form and instructions",
        "publication_date": "2024-07-01",
        "manual_path": "corpus/manual/dnr-542-4000.pdf",
        "fallback_excerpt": "DNR form 542-4000 guides an Iowa confinement producer through the manure management plan. It calls for animal capacity and manure production, manure nutrient concentration, crop rotation and expected yields, nitrogen and phosphorus calculations, soil-test and phosphorus-index information, planned application rates and timing, and identification of land available for application. The acres required cannot be determined from pig count alone; the calculation needs manure production and analysis, crop nutrient needs, soil and phosphorus-index results, and available field information.",
    },
    {
        "title": "Construction Permit Application for Confinement Feeding Operations",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/media/5572/download?inline=",
        "jurisdiction": "Iowa",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official application",
        "publication_date": "2025-01-01",
        "fallback_excerpt": "The Iowa DNR construction permit application package requests owner and site information, proposed animal numbers and animal unit capacity, existing and proposed structures, manure storage type and capacity, separation distances, design information, and required attachments. A producer should not begin a project that requires a permit until DNR has approved the application and issued the permit.",
    },
    {
        "title": "Agricultural Employment",
        "agency": "U.S. Department of Labor",
        "url": "https://www.dol.gov/general/topic/youthlabor/agriculturalemployment",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official guidance",
        "manual_path": "corpus/manual/dol-agricultural-employment.pdf",
        "fallback_excerpt": "Under federal agricultural child labor rules, permissible jobs and hours vary by age. Minors working for a parent on a farm owned or operated by that parent have a statutory exemption. State law may impose tighter restrictions, so employers must also check Iowa requirements.",
    },
    {
        "title": "Fact Sheet #12: Agricultural Employment Under the FLSA",
        "agency": "U.S. Department of Labor, Wage and Hour Division",
        "url": "https://www.dol.gov/agencies/whd/fact-sheets/12-agricultural-employment-flsa",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "fact sheet",
        "publication_date": "2025-01-01",
        "manual_path": "corpus/manual/dol-fact-sheet-12.pdf",
        "fallback_excerpt": "The Fair Labor Standards Act sets federal minimum wage, overtime, recordkeeping, and child labor standards. Agricultural exemptions and the restrictions on employing minors depend on the employer, the worker's age, the work performed, and other facts.",
    },
    {
        "title": "Fact Sheet #40: Child Labor Provisions for Agricultural Occupations",
        "agency": "U.S. Department of Labor, Wage and Hour Division",
        "url": "https://www.dol.gov/agencies/whd/fact-sheets/40-child-labor-farms",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "fact sheet",
        "publication_date": "2016-12-01",
        "manual_path": "corpus/manual/dol-fact-sheet-40.pdf",
        "fallback_excerpt": "Federal agricultural child-labor rules allow youths age 16 and older to work in any farm job at any time. Youths age 14 or 15 may work outside school hours in jobs not declared hazardous. For workers under 16, prohibited agricultural work includes a yard, pen, or stall occupied by a breeding bull or boar, a sow with suckling pigs, or a cow with a newborn calf; working inside a manure pit; specified power-driven machinery; certain tractors; forklifts; toxic agricultural chemicals; explosives; and anhydrous ammonia. A parent-farm exemption and limited training exemptions may apply. Employers must also comply with any more protective state rule.",
    },
    {
        "title": "Agricultural Jobs for 14- and 15-Year-Olds",
        "agency": "U.S. Department of Labor, Wage and Hour Division",
        "url": "https://www.dol.gov/agencies/whd/YouthRules/young-workers/ag-14-15",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official guidance",
        "manual_path": "corpus/manual/dol-ag-jobs-14-15.pdf",
        "fallback_excerpt": "A 14- or 15-year-old may generally work in agriculture only outside school hours and only in nonhazardous jobs. The exact barn-cleaning task matters: entering a manure pit, using specified power-driven equipment, working around a breeding boar, or working with a sow and suckling pigs is federally hazardous for a worker under 16. Once a worker turns 16, the federal agricultural hazardous-occupation restrictions for workers under 16 no longer apply, although Iowa rules and ordinary workplace-safety obligations still need review.",
    },
    {
        "title": "Iowa Child Labor Guidance",
        "agency": "Iowa Department of Inspections, Appeals, and Licensing",
        "url": "https://dial.iowa.gov/hearings/wage-and-child-labor/child-labor",
        "jurisdiction": "Iowa",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "Iowa DIAL's Wage and Child Labor Unit administers Iowa child labor requirements. DIAL states that protections depend on the worker's age, minors must generally be at least 14 to be employed subject to exceptions, and all minor employees are prohibited from certain dangerous tasks or occupations. Employers generally must comply with both Iowa law and the federal Fair Labor Standards Act and follow the most protective provision when they differ. DIAL directs employers to Iowa Code chapter 92 and federal youth-employment rules for the specific job and age.",
    },
    {
        "title": "Iowa Code Chapter 92, Child Labor",
        "agency": "Iowa Legislature",
        "url": "https://www.legis.iowa.gov/docs/code/92.pdf",
        "jurisdiction": "Iowa",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "statute",
        "publication_date": "2026-01-01",
        "fallback_excerpt": "Iowa Code chapter 92 governs child labor. It contains age-based permitted hours and work activities, prohibited work for minors, exceptions, employer duties, and enforcement provisions. Section 92.8 identifies work activities prohibited for persons under eighteen, while other sections address workers under sixteen and work-based learning. The exact barn-cleaning tasks and equipment must be compared with the current statutory list, and an employer covered by both Iowa and federal law must follow the more protective applicable rule.",
    },
    {
        "title": "Disease Alert: African Swine Fever",
        "agency": "USDA Animal and Plant Health Inspection Service",
        "url": "https://www.aphis.usda.gov/livestock-poultry-disease/swine/african-swine-fever",
        "jurisdiction": "Federal",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "disease alert",
        "manual_path": "corpus/manual/aphis-african-swine-fever.pdf",
        "fallback_excerpt": "USDA APHIS describes African Swine Fever as a contagious and deadly viral disease of domestic and feral swine. Possible signs include high fever, decreased appetite and weakness, red or blotchy skin or lesions, diarrhea, vomiting, coughing, difficulty breathing, abortions, and sudden death. Producers who suspect disease should contact their veterinarian promptly to evaluate the animal or herd. Animal health professionals report diagnosed or suspected nationally listed reportable diseases to the APHIS Area Veterinarian in Charge and the State animal health official as applicable.",
    },
    {
        "title": "African Swine Fever: Know the Signs and Symptoms",
        "agency": "USDA Animal and Plant Health Inspection Service",
        "url": "https://www.aphis.usda.gov/sites/default/files/fsc-asf-know-signs.pdf",
        "jurisdiction": "Federal",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official fact sheet",
        "publication_date": "2021-07-01",
        "manual_path": "corpus/manual/aphis-asf-know-signs.pdf",
        "fallback_excerpt": "USDA APHIS lists possible African swine fever signs including high fever, loss of appetite, depression, weakness, red or blotchy skin or lesions, vomiting, diarrhea, coughing or difficulty breathing, abortions, and sudden death. Sick pigs showing these signs should be reported immediately to a veterinarian or animal health officials for appropriate testing and investigation.",
    },
    {
        "title": "Animal and Plant Diseases and Pests of Concern",
        "agency": "USDA Animal and Plant Health Inspection Service",
        "url": "https://www.aphis.usda.gov/laws-regs/animal-plant-diseases-pests-concern",
        "jurisdiction": "Federal",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official disease list",
        "publication_date": "2026-05-11",
        "manual_path": "corpus/manual/aphis-diseases-pests-concern.pdf",
        "fallback_excerpt": "USDA APHIS includes African swine fever virus on its animal diseases and pests of concern list and maintains a high-consequence foreign animal disease list. A producer should treat signs consistent with a foreign animal disease as an urgent veterinary and animal-health reporting matter rather than attempting a diagnosis from symptoms alone.",
    },
    {
        "title": "Agricultural Operations: Hazards and Controls",
        "agency": "Occupational Safety and Health Administration",
        "url": "https://www.osha.gov/agricultural-operations/hazards",
        "jurisdiction": "Federal",
        "topic": "safety",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "OSHA identifies safety, health, biological, environmental, and respiratory hazards in agricultural work. Barns and manure pits can expose workers to acute and chronic respiratory hazards, including bioaerosols and chemical toxicants from animal-waste breakdown.",
    },
    {
        "title": "Veterinary Feed Directive",
        "agency": "U.S. Food and Drug Administration",
        "url": "https://www.fda.gov/animal-veterinary/development-approval-process/veterinary-feed-directive-vfd",
        "jurisdiction": "Federal",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "A veterinary feed directive drug is intended for use in animal feed and may be used only under the professional supervision of a licensed veterinarian. Producers should retain the applicable signed VFD order and use VFD feed only as authorized.",
    },
    {
        "title": "Reportable Animal Diseases",
        "agency": "Iowa Department of Agriculture and Land Stewardship",
        "url": "https://iowaagriculture.gov/animal-industry-division/reportable-animal-diseases",
        "jurisdiction": "Iowa",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official guidance",
        "publication_date": "2026-01-01",
        "fallback_excerpt": "Iowa requires suspected reportable animal diseases to be reported to a Federal Animal Health Official at 866-536-7593 or a State Animal Health Official at 515-281-5305. Iowa lists signs that should be reported immediately, including high illness or death rates, sudden pregnancy loss of unknown cause, severe respiratory conditions, poor response to treatment, unusual necropsy findings, and unusual or unexplained illness. The Iowa 24-hour animal disease emergency hotline is 515-242-0247.",
    },
    {
        "title": "Pseudorabies Guidance for Iowa Swine Producers",
        "agency": "Iowa Department of Agriculture and Land Stewardship",
        "url": "https://iowaagriculture.gov/animal-industry-division/pseudorabies",
        "jurisdiction": "Iowa",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official disease guidance",
        "publication_date": "2026-05-01",
        "fallback_excerpt": "Iowa pork producers who suspect pseudorabies signs should contact their herd veterinarian immediately. Possible cases must also be reported to the Iowa Department of Agriculture and Land Stewardship at 515-281-5305. Signs in swine can include tremors, seizures, paralysis, incoordination, coughing, fever, pneumonia, reproductive problems, and death. Producers should strengthen biosecurity and control movements of people, equipment, clothing, and pigs while animal-health officials investigate.",
    },
    {
        "title": "Iowa Administrative Code Rule 21-64.1, Reporting Animal Disease",
        "agency": "Iowa Legislature",
        "url": "https://www.legis.iowa.gov/docs/iac/rule/02-05-2025.21.64.1.pdf",
        "jurisdiction": "Iowa",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "administrative rule",
        "publication_date": "2025-02-05",
        "fallback_excerpt": "Iowa Administrative Code rule 21-64.1 requires prompt reporting to the Iowa Department of Agriculture and Land Stewardship of a diagnosis or suspected diagnosis of listed infectious or contagious diseases. Aujeszky's disease, also known as pseudorabies, is listed as a multiple-species reportable disease. The swine-disease list includes African swine fever, classical swine fever, Nipah virus encephalitis, porcine cysticercosis, porcine reproductive and respiratory syndrome, swine vesicular disease, and transmissible gastroenteritis.",
    },
    {
        "title": "Iowa Code Chapter 166D, Pseudorabies Control",
        "agency": "Iowa Legislature",
        "url": "https://www.legis.iowa.gov/docs/code/166D.pdf",
        "jurisdiction": "Iowa",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "statute",
        "publication_date": "2026-01-01",
        "fallback_excerpt": "Iowa Code chapter 166D establishes the state's pseudorabies control program. It authorizes testing, epidemiological investigation, quarantine, movement restrictions, herd cleanup, and other measures directed by the Iowa Department of Agriculture and Land Stewardship. The requirements that apply to a particular farm depend on the department's investigation, disease status, and written quarantine or movement instructions.",
    },
    {
        "title": "Iowa General Quarantine Protocol",
        "agency": "Iowa Department of Agriculture and Land Stewardship",
        "url": "https://iowaagriculture.gov/sites/default/files/General%20Quarantine%20Plan%20%2812.30.19%29.pdf",
        "jurisdiction": "Iowa",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official response protocol",
        "publication_date": "2019-12-30",
        "manual_path": "corpus/manual/idals-general-quarantine-protocol.pdf",
        "fallback_excerpt": "Iowa's general animal-disease quarantine protocol provides for legal isolation of diseased, exposed, or susceptible animals and restrictions on movements onto or off quarantined premises. The actual restrictions, control area, testing, cleaning, release criteria, and permitted movements are determined by animal-health officials for the disease and incident.",
    },
    {
        "title": "Iowa Animal Disease Response",
        "agency": "Iowa Department of Agriculture and Land Stewardship",
        "url": "https://iowaagriculture.gov/animal-industry-bureau/animal-disease-response",
        "jurisdiction": "Iowa",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official response guidance",
        "publication_date": "2025-01-01",
        "fallback_excerpt": "During a foreign animal disease response, Iowa may halt susceptible-animal movements, establish control areas, and quarantine farms that are potentially exposed. A quarantine legally prohibits movements on and off the farm. Some movements may later be allowed through written movement permits from state animal-health officials. Iowa may investigate movements of animals, feed, supplies, equipment, personnel, and visitors for at least the prior 30 days.",
    },
    {
        "title": "General Animal and Animal Product Permitting Protocol",
        "agency": "Iowa Department of Agriculture and Land Stewardship",
        "url": "https://iowaagriculture.gov/sites/default/files/animal-industry/pdf/2022/General%20Animal%20Permitting%20Protocol%20%2811.15.2022%29_0.pdf",
        "jurisdiction": "Iowa",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official permitting protocol",
        "publication_date": "2022-11-15",
        "manual_path": "corpus/manual/idals-general-animal-permitting-protocol.pdf",
        "fallback_excerpt": "Iowa's animal movement permitting protocol describes the information and disease-control conditions animal-health officials may require before permitting movement during an outbreak, including premises and destination information, traceability, surveillance testing, biosecurity, epidemiological status, and agreement by receiving authorities. Requirements can change with the disease and incident command.",
    },
    {
        "title": "Secure Pork Supply Continuity of Business Plan",
        "agency": "Secure Pork Supply Plan",
        "url": "https://www.securepork.org/Resources/Secure-Pork-Supply_Plan_for_COB.pdf",
        "jurisdiction": "Federal and state implementation",
        "topic": "animal_health",
        "source_tier": 2,
        "document_type": "official-industry preparedness plan",
        "publication_date": "2026-05-01",
        "manual_path": "corpus/manual/secure-pork-supply-plan.pdf",
        "fallback_excerpt": "Before officials consider a movement permit during an FMD, CSF, or ASF outbreak, a premises should have traceability information including its PIN and coordinates, enhanced biosecurity acceptable to officials, acceptable epidemiological information, no evidence of infection based on surveillance, and an accepting destination. Producers should maintain movement, visitor, vehicle, equipment, health-monitoring, and biosecurity records. Officials determine the actual permit requirements during an outbreak.",
    },
    {
        "title": "Swine Influenza A Virus Resources and Guidance",
        "agency": "USDA Animal and Plant Health Inspection Service",
        "url": "https://www.aphis.usda.gov/livestock-poultry-disease/swine/influenza-a-virus",
        "jurisdiction": "Federal",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official disease guidance",
        "publication_date": "2026-07-15",
        "fallback_excerpt": "USDA APHIS says ordinary swine influenza A virus is not a federally regulated disease and is not required to be reported by the World Organisation for Animal Health. Producers who see respiratory signs should contact their veterinarian, isolate sick pigs if possible, and use biosecurity. Diagnosed or suspected nationally listed reportable diseases are reported by animal-health professionals to federal and state officials as applicable under state law.",
    },
    {
        "title": "Strategies for Reducing Swine Manure Foaming and Safe Manure Management",
        "agency": "Iowa State University Extension and Outreach, Iowa Pork Industry Center",
        "url": "https://www.ipic.iastate.edu/news/strategies-reducing-swine-manure-foaming-and-safe-manure-management",
        "jurisdiction": "Iowa",
        "topic": "safety",
        "source_tier": 2,
        "document_type": "extension safety guidance",
        "publication_date": "2026-02-11",
        "fallback_excerpt": "Iowa State University Extension warns that swine manure foam can trap methane and increase fire and explosion risk. Producers should eliminate ignition sources, avoid welding or open flame near the barn or pit, ventilate before and during agitation, monitor conditions, keep people and animals away from hazardous areas, and use safe agitation and pumping practices. Foam treatments do not replace controls for methane and other manure gases.",
    },
    {
        "title": "Protocols and Preparation for Manure Agitation and Pumping",
        "agency": "University of Minnesota Extension",
        "url": "https://extension.umn.edu/manure-management/manure-agitation-and-pumping",
        "jurisdiction": "Upper Midwest",
        "topic": "safety",
        "source_tier": 2,
        "document_type": "extension safety protocol",
        "fallback_excerpt": "University of Minnesota Extension organizes manure agitation and pumping preparation as evacuate, extinguish, signage, and ventilate. Remove people and, when possible, animals from barns above stored manure; restrict re-entry with signs and barriers; eliminate ignition sources and turn off non-ventilation equipment and pilot lights; and maintain a ventilation plan before and during agitation. For deep-pit swine barns, manage pump-out openings and airflow so gases do not short-circuit into the animal zone. Manure gases, including methane and hydrogen sulfide, can reach dangerous levels during agitation and pumping.",
    },
    {
        "title": "Winter Manure Application Guide",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/media/5845/download?inline=",
        "jurisdiction": "Iowa",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official guidance",
        "publication_date": "2021-05-01",
        "manual_path": "corpus/manual/dnr-winter-manure-application.pdf",
        "fallback_excerpt": "Iowa limits winter land application of liquid manure from confinement operations with more than 500 animal units. Snow-covered-ground restrictions generally run from December 21 through April 1, and frozen-ground restrictions from February 1 through April 1, subject to statutory emergency provisions. All producers must prevent water-quality violations and follow land-application separation distances.",
    },
    {
        "title": "Minimum Separation Distances for Confinement Structures, Form 542-1420",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/media/5566/download?inline=",
        "jurisdiction": "Iowa",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official worksheet and guidance",
        "publication_date": "2024-06-01",
        "manual_path": "corpus/manual/dnr-confinement-separation-distances.pdf",
        "fallback_excerpt": "Iowa DNR form 542-1420 contains the tables for separation distances from residences, businesses, churches, schools, public-use areas, public and private wells, water sources, agricultural drainage wells, sinkholes, wetlands, and roads. The applicable distance depends on the structure type, operation size, date of original construction, and whether an exemption or recorded waiver applies.",
    },
    {
        "title": "Iowa Code Chapter 167, Use and Disposal of Dead Animals",
        "agency": "Iowa Legislature",
        "url": "https://www.legis.iowa.gov/docs/code/167.pdf",
        "jurisdiction": "Iowa",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "statute",
        "publication_date": "2026-01-01",
        "fallback_excerpt": "Iowa Code chapter 167 requires a person caring for or owning an animal that dies to dispose of the carcass within a reasonable time. Authorized methods include delivery to a licensed disposal person and disposal by composting, cooking, burial, or burning as allowed by the chapter and implementing rules. Disease-control officials may direct a different method when needed to prevent disease spread.",
    },
    {
        "title": "Iowa Administrative Code Rule 567-105.6, Composting Dead Farm Animals",
        "agency": "Iowa Legislature",
        "url": "https://www.legis.iowa.gov/docs/iac/rule/567.105.6.pdf",
        "jurisdiction": "Iowa",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "administrative rule",
        "publication_date": "2026-01-01",
        "fallback_excerpt": "Iowa Administrative Code rule 567-105.6 sets operating requirements for composting dead farm animals. Carcasses must enter the composting process within 24 hours of death. The rule specifies base, bulking-agent, and cover layers, control of leachate, odors, and scavengers, decomposition before removal, and land application that minimizes runoff. A business composting animals from sites it neither owns nor operates must obtain a permit.",
    },
    {
        "title": "California Proposition 12 Guidance for Pork Producers",
        "agency": "California Department of Food and Agriculture",
        "url": "https://www.cdfa.ca.gov/AHFSS/AnimalCare/docs/Animal_Care_Producer_Pork.pdf",
        "jurisdiction": "California market requirements",
        "topic": "animal_welfare",
        "source_tier": 1,
        "document_type": "official guidance",
        "publication_date": "2024-01-01",
        "manual_path": "corpus/manual/cdfa-prop12-pork-producer.pdf",
        "fallback_excerpt": "California's Proposition 12 rules apply to out-of-state pork producers keeping breeding pigs to produce whole pork meat from those pigs or their immediate offspring for commercial sale in California. Covered sow farms need compliant confinement, a valid certificate for each farm location, annual renewal, annual on-site inspection, and compliance records retained for two years.",
    },
    {
        "title": "California Proposition 12 Regulatory Framework for Pork",
        "agency": "California Department of Food and Agriculture",
        "url": "https://www.cdfa.ca.gov/AHFSS/AnimalCare/docs/Regulatory_Framework_Pork.pdf",
        "jurisdiction": "California market requirements",
        "topic": "animal_welfare",
        "source_tier": 1,
        "document_type": "official guidance",
        "publication_date": "2024-01-01",
        "manual_path": "corpus/manual/cdfa-prop12-regulatory-framework-pork.pdf",
        "fallback_excerpt": "California's pork framework requires certification and annual on-site inspection for sow farms producing covered pork for California sale. Nursery and finishing sites without breeding pigs do not need producer certification solely for Proposition 12. The distribution chain uses certification, traceable records, and marked shipping documents to establish that covered pork comes from compliant certified producers.",
    },
    {
        "title": "California Proposition 12 Pork Producer On-Site Inspection",
        "agency": "California Department of Food and Agriculture",
        "url": "https://www.cdfa.ca.gov/AHFSS/AnimalCare/docs/prop12_porkproducer_onsiteinspection.pdf",
        "jurisdiction": "California market requirements",
        "topic": "animal_welfare",
        "source_tier": 1,
        "document_type": "official inspection guidance",
        "publication_date": "2024-05-01",
        "manual_path": "corpus/manual/cdfa-prop12-pork-inspection.pdf",
        "fallback_excerpt": "A certifying agent inspects each covered pork-producer location initially and at least once every 12 months for renewal. The inspection reviews facilities, covered breeding pigs, usable floor space, exceptions, and records showing compliance. A knowledgeable representative must be present and able to provide access to records and facilities.",
    },
    {
        "title": "Form I-9, Employment Eligibility Verification",
        "agency": "U.S. Citizenship and Immigration Services",
        "url": "https://www.uscis.gov/sites/default/files/document/forms/i-9.pdf",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official form",
        "publication_date": "2025-01-20",
        "manual_path": "corpus/manual/uscis-form-i9.pdf",
        "fallback_excerpt": "Form I-9 documents identity and employment authorization for new employees. The employee chooses either an acceptable List A document or one acceptable document from List B together with one from List C. Employers may not demand a specific document. The current form includes the official lists of acceptable documents and supplements for preparers, translators, reverification, and rehire.",
    },
    {
        "title": "Instructions for Form I-9",
        "agency": "U.S. Citizenship and Immigration Services",
        "url": "https://www.uscis.gov/sites/default/files/document/forms/i-9instr.pdf",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official instructions",
        "publication_date": "2023-08-01",
        "manual_path": "corpus/manual/uscis-form-i9-instructions-readable.pdf",
        "fallback_excerpt": "USCIS instructs employers to complete Form I-9 for each employee hired for work in the United States, make the instructions and acceptable-document lists available, examine acceptable documents that reasonably appear genuine and relate to the employee, and avoid specifying which documents the employee must present. Employers remain responsible for work completed by an authorized representative.",
    },
    {
        "title": "Employer Responsibilities and Form I-9",
        "agency": "U.S. Citizenship and Immigration Services",
        "url": "https://www.uscis.gov/sites/default/files/document/foia/Employer_Responsibility.pdf",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official employer guide",
        "manual_path": "corpus/manual/uscis-employer-responsibilities-i9.pdf",
        "fallback_excerpt": "USCIS says employers must retain Form I-9 while the person works for the employer. After employment ends, retain it until the later of three years after the date of hire or one year after termination. Employers who copy supporting documents must store those copies for the same retention period. Employers generally examine original documents and may not tell an employee which acceptable documents to present.",
    },
    {
        "title": "H-2A Temporary Certification for Agriculture Workers",
        "agency": "U.S. Department of Labor, Office of Foreign Labor Certification",
        "url": "https://flag.dol.gov/index.php/programs/H-2A",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official program guidance",
        "publication_date": "2026-01-01",
        "fallback_excerpt": "The H-2A program covers full-time agricultural work for which the employer's need is temporary or seasonal. Seasonal work is tied to a recurring event or pattern and requires labor above ongoing operations. Temporary need ordinarily lasts no more than one year and is normally ten months or less. A permanent year-round need at a hog operation generally does not satisfy that test, although a genuinely temporary or seasonal livestock need is evaluated on its facts.",
    },
]

ALLOWED_HOST_SUFFIXES = (
    "iowadnr.gov",
    "legis.iowa.gov",
    "dol.gov",
    "aphis.usda.gov",
    "osha.gov",
    "fda.gov",
    "usda.gov",
    "epa.gov",
    "cdc.gov",
    "iowaagriculture.gov",
    "iowaworkforcedevelopment.gov",
    "dial.iowa.gov",
    "iastate.edu",
    "porkcheckoff.org",
    "securepork.org",
    "cdfa.ca.gov",
    "uscis.gov",
    "flag.dol.gov",
    "extension.umn.edu",
)
