"""Approved Nebraska-first sources. Fallback excerpts summarize the linked authority."""

APPROVED_SOURCES = [
    {
        "title": "Livestock Waste Control Program",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/land-waste/agriculture/livestock-waste-control-program",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official program guidance",
        "fallback_excerpt": "Nebraska's Livestock Waste Control Program administers state Construction and Operating Permits and federal NPDES permits for animal feeding operations. Medium and large operations that have not already been permitted, approved, exempted, or inspected must request an initial inspection. If livestock waste control facilities are required, the operation must submit the permit application specified by the Department before construction or modification.",
    },
    {
        "title": "Title 130, Livestock Waste Control Regulations",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/sites/default/files/titles/Title%20130%20Effective%2010-04-2011.pdf",
        "jurisdiction": "Nebraska",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "administrative regulation",
        "effective_date": "2011-10-04",
        "manual_path": "corpus/manual/nebraska-title-130.pdf",
        "fallback_excerpt": "Title 130 governs Nebraska animal feeding operations, livestock waste control facilities, permit applications, discharges, nutrient management plans, land application, inspections, monitoring, records, closure, and enforcement. Requirements depend on the operation's animal capacity, discharge status, waste-control facilities, permit status, and proposed construction or modification.",
    },
    {
        "title": "Proposed 2026 Amendments to Title 130",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/resources-services/laws-regulations/environmental-quality-council/draft-and-proposed-rules-and/livestock-waste-control-regulations-0",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official proposed-rule docket",
        "publication_date": "2026-06-24",
        "fallback_excerpt": "DWEE lists the 2026 Title 130 material under Draft and Proposed Rules and Regulations and identifies June 24, 2026 as the Environmental Quality Council hearing date. The docket does not present the proposal as the current effective Title 130. The separately published regulation effective October 4, 2011 remains the controlling text unless Nebraska completes the rulemaking process and publishes a later effective version.",
    },
    {
        "title": "Livestock Program Forms and Guidance",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/forms/publications-grants-forms?combine=&form_type=All&program=204",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "forms index",
        "fallback_excerpt": "The Department's livestock-program forms index provides inspection requests, permit applications, discharge notification, nutrient management forms, mortality management supplements, annual-report guidance, land-application training, recordkeeping guidance, and construction resources.",
    },
    {
        "title": "Animal Feeding Operation Categories and Fees",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/sites/default/files/publications/05-006-Animal_Feeding_Operation_%28AFO%29_Categories_Fees_0.pdf",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official guidance",
        "publication_date": "2022-03-01",
        "manual_path": "corpus/manual/nebraska-afo-categories-fees.pdf",
        "fallback_excerpt": "Nebraska classifies swine operations with pigs weighing 55 pounds or more as large at 2,500 head and medium at 750 through 2,499 head. Operations with swine under 55 pounds are large at 10,000 head and medium at 3,000 through 9,999 head. The guidance explains inspection, application, annual permit, and late fees and states that inspection is required before construction or expansion unless the operation is exempt.",
    },
    {
        "title": "Form A, Request for Inspection of Animal Feeding Operation",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/sites/default/files/publications/Form%20A%20-%20Inspection%20Request%20_0.pdf",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official form",
        "manual_path": "corpus/manual/nebraska-form-a-inspection.pdf",
        "fallback_excerpt": "Form A requests a Department inspection for a proposed new operation, expansion, existing uninspected operation, major operational change, prior discharge, or other stated reason. It asks for the operation location, animal types and maximum capacity, housing type, waste-control facilities, land application area, and proposed construction date.",
    },
    {
        "title": "Form B, Livestock Waste Control Permit Application",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/sites/default/files/publications/Form%20B%20Application.pdf",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official form",
        "manual_path": "corpus/manual/nebraska-form-b-permit.pdf",
        "fallback_excerpt": "Form B is used for new or modified Construction and Operating Permits and NPDES permit coverage. It requests applicant, location, animal-capacity, and technical-advisor information and states that the applicant remains responsible for local laws and applicable local and county permits.",
    },
    {
        "title": "Livestock Waste Control Program Fees",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/livestock-waste-control-program-fees",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official fee guidance",
        "fallback_excerpt": "Nebraska's livestock program assesses initial-inspection, permit-application, and annual permit fees. All medium and large animal feeding operations must request an initial inspection if they have not already been inspected. The inspection must occur before construction and before a Construction and Operating Permit application is submitted. Permitted large CAFOs and operations with NPDES permits owe annual fees by March 1.",
    },
    {
        "title": "Notification of Discharge of Livestock Waste",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/sites/default/files/publications/00-049%20Notification%20of%20Discharge%20of%20Livestock%20Waste%20Form.pdf",
        "jurisdiction": "Nebraska",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official reporting form",
        "publication_date": "2016-11-01",
        "manual_path": "corpus/manual/nebraska-discharge-notification.pdf",
        "fallback_excerpt": "Title 130 requires verbal notification to the Department within 24 hours after becoming aware of a discharge or anticipated discharge of livestock waste and a written report within five days. The form asks for the cause, flow path, receiving water, dates, estimated volume, damage, response actions, environmental effects, and any sampling results.",
    },
    {
        "title": "Report an Environmental Pollution Problem or Complaint",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/about/contact-us/report-environmental-pollution-problem-or-complaint",
        "jurisdiction": "Nebraska",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official emergency guidance",
        "fallback_excerpt": "For acute spills and environmental emergencies during business hours, Nebraska directs callers to the Department at 402-471-2186 or 877-253-2603. After hours, weekends, and holidays, contact Nebraska State Patrol Dispatch at 402-479-4921. Reports should describe the problem, time, location, cause, awareness, and environmental impact.",
    },
    {
        "title": "Narrative Rate Approach Nutrient Management Plan Outline",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/sites/default/files/publications/11-022-Narrative-Rate-Approach-Nutrient-Management-Plan-Outline.pdf",
        "jurisdiction": "Nebraska",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official guidance",
        "publication_date": "2021-10-01",
        "manual_path": "corpus/manual/nebraska-nmp-outline.pdf",
        "fallback_excerpt": "Nebraska's nutrient management plan outline covers operation maps, water sources, waste facilities, storage sizing, mortality and chemical management, land-application sites, soil and manure sampling, crop nutrient needs, application rates, phosphorus risk, setbacks, transfer agreements, inspections, records, and emergency procedures.",
    },
    {
        "title": "Record Keeping Guidance for Concentrated Animal Feeding Operations",
        "agency": "Nebraska Department of Water, Energy, and Environment",
        "url": "https://dwee.nebraska.gov/sites/default/files/publications/05-123-Recordkeeping_Concentrated_AFO.pdf",
        "jurisdiction": "Nebraska",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official guidance",
        "publication_date": "2022-04-15",
        "manual_path": "corpus/manual/nebraska-cafo-recordkeeping.pdf",
        "fallback_excerpt": "Permitted Nebraska CAFOs must retain records supporting nutrient-management implementation, production-area inspections, mortalities, storage levels, manure and soil sampling, land application, transfers, equipment calibration, training, and corrective actions for the period specified by Title 130 and the permit.",
    },
    {
        "title": "Nebraska Revised Statute 54-2417, Livestock Waste Management Definitions",
        "agency": "Nebraska Legislature",
        "url": "https://nebraskalegislature.gov/laws/statutes.php?statute=54-2417",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "statute",
        "fallback_excerpt": "The Livestock Waste Management Act defines an animal feeding operation, livestock waste control facility, major modification, state Construction and Operating Permit, and NPDES permit. A major modification includes changes in location, animal numbers or species, waste treatment, storage, land application, or the size or location of the waste-control facility.",
    },
    {
        "title": "Nebraska Revised Statute 54-2423, Inspection Requests",
        "agency": "Nebraska Legislature",
        "url": "https://nebraskalegislature.gov/laws/statutes.php?statute=54-2423",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "statute",
        "fallback_excerpt": "An animal feeding operation that lacks a permit, construction approval, exemption, or prior determination must request a Department inspection to decide whether a livestock waste control facility is required. Inspection fees are set according to the operation category.",
    },
    {
        "title": "Nebraska Revised Statute 54-2432, Prohibited Livestock Waste Acts",
        "agency": "Nebraska Legislature",
        "url": "https://nebraskalegislature.gov/laws/statutes.php?statute=54-2432",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "statute",
        "fallback_excerpt": "Nebraska prohibits constructing or operating an animal feeding operation before required inspection, constructing a livestock waste control facility without the required permit, operating before an approved waste-control facility is built, discharging livestock waste without required authorization, and violating permit terms or the Livestock Waste Management Act.",
    },
    {
        "title": "Nebraska Revised Statute 54-2435, Livestock Waste Rules",
        "agency": "Nebraska Legislature",
        "url": "https://nebraskalegislature.gov/laws/statutes.php?statute=54-2435",
        "jurisdiction": "Nebraska",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "statute",
        "fallback_excerpt": "Nebraska law directs the Environmental Quality Council to adopt animal-feeding-operation rules covering location restrictions and setbacks, inspection requests, animal numbers, waste-control facilities, design, construction, operation, monitoring, nutrient management plans, fees, exemptions, and discharge proceedings.",
    },
    {
        "title": "Nebraska Revised Statute 54-2437, County Conditional Use Permits",
        "agency": "Nebraska Legislature",
        "url": "https://nebraskalegislature.gov/laws/statutes.php?statute=54-2437",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "statute",
        "fallback_excerpt": "Nebraska law addresses when county planning commissions or county boards must grant a conditional use permit or special exception for certain modifications to existing animal feeding operations made to comply with waste-management requirements. Other proposed livestock construction remains subject to the applicable county zoning rules.",
    },
    {
        "title": "Nebraska Revised Statute 23-114.01, County Livestock Conditional Uses",
        "agency": "Nebraska Legislature",
        "url": "https://nebraskalegislature.gov/laws/statutes.php?statute=23-114.01",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "statute",
        "fallback_excerpt": "A Nebraska livestock applicant may request a timely determination of the conditions a county will impose on a conditional use permit or special exception. Approval is based on county zoning regulations and does not release the applicant from separate local, state, or federal permit requirements.",
    },
    {
        "title": "Livestock Siting Assessment Matrix",
        "agency": "Nebraska Department of Agriculture",
        "url": "https://nda.nebraska.gov/promotion/livestock_matrix",
        "jurisdiction": "Nebraska",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "official county siting guidance",
        "fallback_excerpt": "Nebraska's Livestock Siting Assessment Matrix is an optional tool for county officials evaluating conditional-use or special-exception applications. It includes information about separation distances, animal units, and other siting criteria, but the controlling local requirements come from the county's adopted zoning rules.",
    },
    {
        "title": "Nebraska Revised Statute 54-2946, Dead Animal Disposal",
        "agency": "Nebraska Legislature",
        "url": "https://nebraskalegislature.gov/laws/statutes.php?statute=54-2946",
        "jurisdiction": "Nebraska",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "statute",
        "fallback_excerpt": "Nebraska requires an owner or custodian to properly dispose of a dead animal within 36 hours after learning of the death unless a different timeframe is authorized. Permitted methods include specified on-site burial, incineration, on-site composting, approved transport, diagnostic transport, and other methods authorized by the State Veterinarian. Special restrictions apply when anthrax is suspected.",
    },
    {
        "title": "Livestock Disease Reporting",
        "agency": "Nebraska Department of Agriculture",
        "url": "https://nda.nebraska.gov/animal/reporting",
        "jurisdiction": "Nebraska",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official disease reporting portal",
        "fallback_excerpt": "Nebraska's livestock disease reporting portal provides the current reportable-disease list, reporting form, regulations, and surveillance reports. Disease categories determine whether reporting is immediate or monthly.",
    },
    {
        "title": "Nebraska Animal Health Regulations",
        "agency": "Nebraska Department of Agriculture",
        "url": "https://nda.nebraska.gov/sites/default/files/regulations/animal/AnimalRegulations.pdf",
        "jurisdiction": "Nebraska",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "administrative regulation",
        "publication_date": "2026-05-01",
        "manual_path": "corpus/manual/nebraska-animal-regulations-searchable.pdf",
        "fallback_excerpt": "Nebraska animal-health regulations classify reportable diseases and establish reporting, quarantine, movement, testing, and disease-control requirements. A person suspecting a foreign animal disease, emergency condition, program disease, or immediately reportable disease must notify the State Veterinarian as required by the rule.",
    },
    {
        "title": "Nebraska Livestock Disease Reporting List",
        "agency": "Nebraska Department of Agriculture",
        "url": "https://nda.nebraska.gov/sites/default/files/animal/reporting/disease_list.pdf",
        "jurisdiction": "Nebraska",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official disease list",
        "publication_date": "2026-05-01",
        "manual_path": "corpus/manual/nebraska-reportable-disease-list.pdf",
        "fallback_excerpt": "Nebraska lists African swine fever, classical swine fever, foot-and-mouth disease, Japanese encephalitis, Nipah virus encephalitis, and other foreign animal diseases for immediate reporting. The list also categorizes porcine program and monitored diseases, including pseudorabies, brucellosis, Senecavirus A, and PRRS.",
    },
    {
        "title": "African Swine Fever",
        "agency": "Nebraska Department of Agriculture",
        "url": "https://nda.nebraska.gov/animal/diseases/asf",
        "jurisdiction": "Nebraska",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official disease guidance",
        "fallback_excerpt": "Nebraska identifies African swine fever as a serious contagious disease of pigs and links producers to recognition, prevention, biosecurity, and reporting resources. Suspected foreign animal disease should be reported immediately through a veterinarian and state or federal animal-health officials.",
    },
    {
        "title": "Senecavirus A in Swine",
        "agency": "Nebraska Department of Agriculture",
        "url": "https://nda.nebraska.gov/animal/diseases/svv",
        "jurisdiction": "Nebraska",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official disease guidance",
        "fallback_excerpt": "Senecavirus A can cause vesicles on the snout, mouth, and coronary bands that cannot be visually distinguished from foot-and-mouth disease. Nebraska directs producers to contact a veterinarian immediately and reports suspected cases to the State Veterinarian so foreign animal disease can be ruled out.",
    },
    {
        "title": "Nebraska Swine Import Requirements",
        "agency": "Nebraska Department of Agriculture",
        "url": "https://nda.nebraska.gov/animal/imports/swine",
        "jurisdiction": "Nebraska",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official import guidance",
        "fallback_excerpt": "Swine entering Nebraska generally require a certificate of veterinary inspection issued within 30 days, accepted identification, origin and destination information, and compliance with pseudorabies and movement conditions. Requirements vary for breeding, feeding, exhibition, and slaughter movements.",
    },
    {
        "title": "Employment of Minors",
        "agency": "Nebraska Department of Labor",
        "url": "https://dol.nebraska.gov/LaborStandards/WorkerRights/EmploymentOfMinors",
        "jurisdiction": "Nebraska",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "Nebraska employers must consider both state and federal child-labor requirements and follow the more restrictive applicable rule. State guidance addresses employment certificates, hours for workers under 16, dangerous work, and special permits. Federal agricultural hazardous-occupation rules separately restrict tasks for workers under 16.",
    },
    {
        "title": "Nebraska Employment of Minors Fact Sheet",
        "agency": "Nebraska Department of Labor",
        "url": "https://dol.nebraska.gov/webdocs/getfile/3db852c8-65db-4ac1-b52d-d41ec46288a0",
        "jurisdiction": "Nebraska",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official fact sheet",
        "publication_date": "2025-09-01",
        "manual_path": "corpus/manual/nebraska-employment-minors.pdf",
        "fallback_excerpt": "Nebraska's fact sheet compares state and federal hours for 14- and 15-year-olds, explains employment-certificate requirements and exceptions, and directs employers to apply the more stringent standard when both laws cover the work.",
    },
    {
        "title": "Nebraska Revised Statute 48-302, Employment Certificates",
        "agency": "Nebraska Legislature",
        "url": "https://nebraskalegislature.gov/laws/statutes.php?statute=48-302",
        "jurisdiction": "Nebraska",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "statute",
        "effective_date": "2026-07-18",
        "fallback_excerpt": "Nebraska generally requires an employer of a child under 16 to obtain and keep an employment certificate and a list of covered child employees. The certificate must be retained for at least 12 months after employment ends or the child reaches 16. Statutory definitions and exemptions must be checked for the specific agricultural job.",
    },
    {
        "title": "Nebraska Revised Statute 48-310, Working Hours for Children Under 16",
        "agency": "Nebraska Legislature",
        "url": "https://nebraskalegislature.gov/laws/statutes.php?statute=48-310",
        "jurisdiction": "Nebraska",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "statute",
        "fallback_excerpt": "Nebraska limits covered employment of workers under 16 to 48 hours per week and eight hours per day and restricts the time of day they may work. Federal limits can be more protective and must be applied when federal law covers the employment.",
    },
    {
        "title": "Nebraska Revised Statute 48-313, Dangerous Work for Children",
        "agency": "Nebraska Legislature",
        "url": "https://nebraskalegislature.gov/laws/statutes.php?statute=48-313",
        "jurisdiction": "Nebraska",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "statute",
        "fallback_excerpt": "Nebraska prohibits employing a child under 16 in work that is dangerous to life or limb, may injure health, or may deprave morals. The exact task and workplace must also be checked against the federal agricultural hazardous-occupation rules.",
    },
    {
        "title": "Farm Labor Contractors",
        "agency": "Nebraska Department of Labor",
        "url": "https://dol.nebraska.gov/LaborStandards/Compliance/FarmLaborContractor",
        "jurisdiction": "Nebraska",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official licensing guidance",
        "fallback_excerpt": "Nebraska requires farm labor contractors to obtain a state license before engaging in farm labor contracting activity. The Department provides the application, exemption application, required practices, and contact information.",
    },
    {
        "title": "Manure Nutrient Production and Land Requirements",
        "agency": "University of Nebraska-Lincoln Extension",
        "url": "https://water.unl.edu/manure/nutrient-production/",
        "jurisdiction": "Nebraska",
        "topic": "manure",
        "source_tier": 2,
        "document_type": "extension guidance",
        "fallback_excerpt": "UNL explains that land needs depend on manure quantity, nitrogen and phosphorus content, storage and application losses, crop nutrient needs, and agronomic application rates. Its planning tools estimate whether sufficient land is available and identify manure nutrients that must be transferred to off-farm users.",
    },
    {
        "title": "Nebraska Manure Regulations and Recordkeeping",
        "agency": "University of Nebraska-Lincoln Extension",
        "url": "https://water.unl.edu/land-application-training-online/manure-regulations/recordkeeping/",
        "jurisdiction": "Nebraska",
        "topic": "manure",
        "source_tier": 2,
        "document_type": "extension compliance guidance",
        "fallback_excerpt": "UNL explains that Title 130 requires records documenting nutrient-plan implementation, production-area inspections, manure application, manure and soil analyses, field maps, equipment calibration, training, and transfers. Records for permitted operations are generally retained for five years and must be available to inspectors.",
    },
    {
        "title": "Nebraska Nutrient Management Plan Tools",
        "agency": "University of Nebraska-Lincoln Extension",
        "url": "https://water.unl.edu/manure/nmp-tools/",
        "jurisdiction": "Nebraska",
        "topic": "manure",
        "source_tier": 2,
        "document_type": "extension planning guidance",
        "fallback_excerpt": "UNL nutrient-management tools cover animal and land inventories, manure nutrient production and land needs, manure transfer agreements, emergency response, crop requirements, application rates, soil and manure sampling, field plans, and annual records.",
    },
    {
        "title": "Agricultural Employment",
        "agency": "U.S. Department of Labor",
        "url": "https://www.dol.gov/general/topic/youthlabor/agriculturalemployment",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official guidance",
        "manual_path": "corpus/manual/dol-agricultural-employment.pdf",
        "fallback_excerpt": "Federal agricultural child-labor rules depend on age, school hours, relationship to the farm owner, and the exact task. Youths 16 and older may perform any farm job under the federal agricultural child-labor rules. Workers under 16 may perform only nonhazardous agricultural jobs outside school hours unless an exemption applies.",
    },
    {
        "title": "Fact Sheet 12, Agricultural Employment Under the FLSA",
        "agency": "U.S. Department of Labor, Wage and Hour Division",
        "url": "https://www.dol.gov/agencies/whd/fact-sheets/12-agricultural-employment-flsa",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official fact sheet",
        "publication_date": "2025-01-01",
        "manual_path": "corpus/manual/dol-fact-sheet-12.pdf",
        "fallback_excerpt": "Federal agricultural employment rules address minimum wage, overtime exemptions, youth employment, recordkeeping, housing, transportation, and interactions with other federal and state requirements.",
    },
    {
        "title": "Fact Sheet 40, Child Labor in Agricultural Occupations",
        "agency": "U.S. Department of Labor, Wage and Hour Division",
        "url": "https://www.dol.gov/agencies/whd/fact-sheets/40-child-labor-farms",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official fact sheet",
        "publication_date": "2016-12-01",
        "manual_path": "corpus/manual/dol-fact-sheet-40.pdf",
        "fallback_excerpt": "Federal rules prohibit workers under 16 from hazardous agricultural tasks including entering manure pits, operating specified power-driven machinery, using certain tractors and forklifts, handling specified chemicals, and working in a pen with a breeding boar or a sow with suckling pigs. Parent-farm and limited training exemptions may apply.",
    },
    {
        "title": "Agricultural Jobs for 14- and 15-Year-Olds",
        "agency": "U.S. Department of Labor, Wage and Hour Division",
        "url": "https://www.dol.gov/agencies/whd/YouthRules/young-workers/ag-14-15",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official guidance",
        "manual_path": "corpus/manual/dol-ag-jobs-14-15.pdf",
        "fallback_excerpt": "A 14- or 15-year-old may generally work in agriculture outside school hours in nonhazardous jobs. The exact barn-cleaning task matters because manure pits, specified machinery, breeding boars, and sows with suckling pigs are federally hazardous for workers under 16.",
    },
    {
        "title": "Agricultural Operations: Hazards and Controls",
        "agency": "Occupational Safety and Health Administration",
        "url": "https://www.osha.gov/agricultural-operations/hazards",
        "jurisdiction": "Federal",
        "topic": "safety",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "OSHA identifies safety, respiratory, biological, chemical, electrical, machinery, and confined-space hazards in agricultural operations. Manure decomposition can create acute respiratory and toxic-gas hazards that require task-specific controls and training.",
    },
    {
        "title": "A Beginner's Guide to Manure Spreaders",
        "agency": "University of Nebraska-Lincoln Extension",
        "url": "https://water.unl.edu/beginners-guide-manure-spreaders-ensuring-even-application-healthy-fields/",
        "jurisdiction": "Nebraska",
        "topic": "safety",
        "source_tier": 2,
        "document_type": "extension safety guidance",
        "publication_date": "2025-03-01",
        "fallback_excerpt": "Nebraska Extension warns that liquid manure handling can release dangerous gases, especially hydrogen sulfide. Before and during manure agitation, adequately ventilate barns and every area where people or animals may be present. Hydrogen sulfide is heavier than air and can accumulate near ground level under unfavorable atmospheric conditions.",
    },
    {
        "title": "Veterinary Feed Directive",
        "agency": "U.S. Food and Drug Administration",
        "url": "https://www.fda.gov/animal-veterinary/development-approval-process/veterinary-feed-directive-vfd",
        "jurisdiction": "Federal",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "Veterinary Feed Directive drugs may be used in animal feed only under the professional supervision of a licensed veterinarian. Producers should retain the signed VFD order and use VFD feed only as authorized.",
    },
    {
        "title": "Disease Alert: African Swine Fever",
        "agency": "USDA Animal and Plant Health Inspection Service",
        "url": "https://www.aphis.usda.gov/livestock-poultry-disease/swine/african-swine-fever",
        "jurisdiction": "Federal",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "disease alert",
        "manual_path": "corpus/manual/aphis-african-swine-fever.pdf",
        "fallback_excerpt": "USDA describes African swine fever as a contagious and deadly viral disease of domestic and feral swine. Producers who suspect disease should contact their veterinarian and state or federal animal-health officials promptly for investigation and testing.",
    },
    {
        "title": "African Swine Fever: Know the Signs and Symptoms",
        "agency": "USDA Animal and Plant Health Inspection Service",
        "url": "https://www.aphis.usda.gov/sites/default/files/fsc-asf-know-signs.pdf",
        "jurisdiction": "Federal",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official fact sheet",
        "publication_date": "2021-07-01",
        "manual_path": "corpus/manual/aphis-asf-know-signs.pdf",
        "fallback_excerpt": "Possible African swine fever signs include high fever, appetite loss, weakness, red or blotchy skin, vomiting, diarrhea, coughing, breathing difficulty, abortions, and sudden death. Sick pigs showing these signs should be reported immediately to a veterinarian or animal-health official.",
    },
    {
        "title": "Secure Pork Supply Continuity of Business Plan",
        "agency": "Secure Pork Supply Plan",
        "url": "https://www.securepork.org/Resources/Secure-Pork-Supply_Plan_for_COB.pdf",
        "jurisdiction": "Federal and state implementation",
        "topic": "animal_health",
        "source_tier": 2,
        "document_type": "official-industry preparedness plan",
        "publication_date": "2026-05-01",
        "manual_path": "corpus/manual/secure-pork-supply-plan.pdf",
        "fallback_excerpt": "The Secure Pork Supply plan helps operations prepare for movement permitting during a foreign animal disease response. Preparedness includes a premises identification number, enhanced biosecurity plan, movement records, surveillance, and compliance with incident-specific state and federal requirements.",
    },
    {
        "title": "California Proposition 12 Guidance for Pork Producers",
        "agency": "California Department of Food and Agriculture",
        "url": "https://www.cdfa.ca.gov/AHFSS/AnimalCare/docs/Animal_Care_Producer_Pork.pdf",
        "jurisdiction": "California market requirements",
        "topic": "animal_welfare",
        "source_tier": 1,
        "document_type": "official guidance",
        "publication_date": "2024-01-01",
        "manual_path": "corpus/manual/cdfa-prop12-pork-producer.pdf",
        "fallback_excerpt": "Proposition 12 requirements can apply to covered pork sold in California even when pigs are raised in Nebraska. Applicability depends on the animal class, production purpose, housing, certification, records, and destination market.",
    },
    {
        "title": "California Proposition 12 Regulatory Framework for Pork",
        "agency": "California Department of Food and Agriculture",
        "url": "https://www.cdfa.ca.gov/AHFSS/AnimalCare/docs/Regulatory_Framework_Pork.pdf",
        "jurisdiction": "California market requirements",
        "topic": "animal_welfare",
        "source_tier": 1,
        "document_type": "official regulatory guidance",
        "publication_date": "2024-01-01",
        "manual_path": "corpus/manual/cdfa-prop12-regulatory-framework-pork.pdf",
        "fallback_excerpt": "California's framework explains certification, distributor registration, supply-chain documentation, covered pork, breeding pigs, confinement standards, records, inspections, and exceptions for pork entering the California market.",
    },
    {
        "title": "Form I-9, Employment Eligibility Verification",
        "agency": "U.S. Citizenship and Immigration Services",
        "url": "https://www.uscis.gov/sites/default/files/document/forms/i-9.pdf",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official form",
        "publication_date": "2025-01-20",
        "manual_path": "corpus/manual/uscis-form-i9.pdf",
        "fallback_excerpt": "Employers complete Form I-9 for each employee hired for work in the United States. The employee chooses acceptable documents, and the employer may not demand a specific document.",
    },
    {
        "title": "Instructions for Form I-9",
        "agency": "U.S. Citizenship and Immigration Services",
        "url": "https://www.uscis.gov/sites/default/files/document/forms/i-9instr.pdf",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official instructions",
        "publication_date": "2023-08-01",
        "manual_path": "corpus/manual/uscis-form-i9-instructions-readable.pdf",
        "fallback_excerpt": "USCIS instructions explain completion, document review, reverification, rehire, corrections, storage, and prohibited document practices for Form I-9.",
    },
    {
        "title": "Employer Responsibilities and Form I-9",
        "agency": "U.S. Citizenship and Immigration Services",
        "url": "https://www.uscis.gov/sites/default/files/document/foia/Employer_Responsibility.pdf",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official employer guide",
        "manual_path": "corpus/manual/uscis-employer-responsibilities-i9.pdf",
        "fallback_excerpt": "Employers retain Form I-9 while a person works and, after employment ends, until the later of three years after hire or one year after termination. Supporting-document copies, when retained, follow the same retention period.",
    },
    {
        "title": "H-2A Temporary Certification for Agriculture Workers",
        "agency": "U.S. Department of Labor, Office of Foreign Labor Certification",
        "url": "https://flag.dol.gov/index.php/programs/H-2A",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official program guidance",
        "publication_date": "2026-01-01",
        "fallback_excerpt": "H-2A covers full-time agricultural work when the employer's need is temporary or seasonal. A permanent year-round need ordinarily does not qualify, while a genuinely temporary or seasonal livestock need depends on the facts and program requirements.",
    },
]


ALLOWED_HOST_SUFFIXES = (
    "dwee.nebraska.gov",
    "dee.nebraska.gov",
    "nebraskalegislature.gov",
    "nda.nebraska.gov",
    "dol.nebraska.gov",
    "water.unl.edu",
    "unl.edu",
    "dol.gov",
    "aphis.usda.gov",
    "osha.gov",
    "fda.gov",
    "usda.gov",
    "epa.gov",
    "cdc.gov",
    "porkcheckoff.org",
    "securepork.org",
    "cdfa.ca.gov",
    "uscis.gov",
    "flag.dol.gov",
)
