"""Approved starter sources. Fallback excerpts are public-agency summaries, not model output."""

APPROVED_SOURCES = [
    {
        "title": "Manure Management Plans",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/environmental-protection/animal-feeding-operations/afo-confinements/manure-management-plans",
        "jurisdiction": "Iowa",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "Iowa DNR explains which confinement feeding operations must submit manure management plans, when original and annual plans are due, where copies must be maintained, and which manure application records must be retained. Producers with MMPs must use certified manure applicators. Manure application records are to be kept for five years and made available to DNR on request.",
    },
    {
        "title": "Animal Feeding Operation Forms",
        "agency": "Iowa Department of Natural Resources",
        "url": "https://www.iowadnr.gov/environmental-protection/animal-feeding-operations/afo-forms",
        "jurisdiction": "Iowa",
        "topic": "manure",
        "source_tier": 1,
        "document_type": "forms index",
        "fallback_excerpt": "Iowa DNR's official forms index links manure management plan forms, annual update forms, manure application recordkeeping forms, construction and expansion forms, permit applications, fee forms, and spill reporting guidance for animal feeding operations.",
    },
    {
        "title": "Iowa Code Chapter 459, Animal Agriculture Compliance Act",
        "agency": "Iowa Legislature",
        "url": "https://www.legis.iowa.gov/docs/code/459.pdf",
        "jurisdiction": "Iowa",
        "topic": "permits",
        "source_tier": 1,
        "document_type": "statute",
        "publication_date": "2026-01-01",
        "fallback_excerpt": "Iowa Code chapter 459 is the Animal Agriculture Compliance Act. It contains statutory definitions and requirements concerning confinement feeding operations, construction permits, manure management plans, separation distances, compliance, and enforcement. The current code text must be checked for the facts of a specific operation.",
    },
    {
        "title": "Agricultural Employment",
        "agency": "U.S. Department of Labor",
        "url": "https://www.dol.gov/general/topic/youthlabor/agriculturalemployment",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "Under federal agricultural child labor rules, permissible jobs and hours vary by age. Minors working for a parent on a farm owned or operated by that parent have a statutory exemption. State law may impose tighter restrictions, so employers must also check Iowa requirements.",
    },
    {
        "title": "Fact Sheet #12: Agricultural Employment Under the FLSA",
        "agency": "U.S. Department of Labor, Wage and Hour Division",
        "url": "https://www.dol.gov/agencies/whd/fact-sheets/12-agricultural-employment-flsa",
        "jurisdiction": "Federal",
        "topic": "labor",
        "source_tier": 1,
        "document_type": "fact sheet",
        "fallback_excerpt": "The Fair Labor Standards Act sets federal minimum wage, overtime, recordkeeping, and child labor standards. Agricultural exemptions and the restrictions on employing minors depend on the employer, the worker's age, the work performed, and other facts.",
    },
    {
        "title": "Disease Alert: African Swine Fever",
        "agency": "USDA Animal and Plant Health Inspection Service",
        "url": "https://www.aphis.usda.gov/livestock-poultry-disease/swine/african-swine-fever",
        "jurisdiction": "Federal",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "disease alert",
        "fallback_excerpt": "USDA APHIS lists possible African Swine Fever signs including high fever, decreased appetite and weakness, red or blotchy skin or lesions, diarrhea, vomiting, coughing, difficulty breathing, abortions, and sudden death. Producers who suspect an animal disease should contact their veterinarian to evaluate the animal or herd.",
    },
    {
        "title": "Agricultural Operations: Hazards and Controls",
        "agency": "Occupational Safety and Health Administration",
        "url": "https://www.osha.gov/agricultural-operations/hazards",
        "jurisdiction": "Federal",
        "topic": "safety",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "OSHA identifies safety, health, biological, environmental, and respiratory hazards in agricultural work. Barns and manure pits can expose workers to acute and chronic respiratory hazards, including bioaerosols and chemical toxicants from animal-waste breakdown.",
    },
    {
        "title": "Veterinary Feed Directive",
        "agency": "U.S. Food and Drug Administration",
        "url": "https://www.fda.gov/animal-veterinary/development-approval-process/veterinary-feed-directive-vfd",
        "jurisdiction": "Federal",
        "topic": "animal_health",
        "source_tier": 1,
        "document_type": "official guidance",
        "fallback_excerpt": "A veterinary feed directive drug is intended for use in animal feed and may be used only under the professional supervision of a licensed veterinarian. Producers should retain the applicable signed VFD order and use VFD feed only as authorized.",
    },
]

ALLOWED_HOST_SUFFIXES = (
    "iowadnr.gov",
    "legis.iowa.gov",
    "dol.gov",
    "aphis.usda.gov",
    "osha.gov",
    "fda.gov",
    "usda.gov",
    "epa.gov",
    "cdc.gov",
    "iowaagriculture.gov",
    "iowaworkforcedevelopment.gov",
    "iastate.edu",
    "porkcheckoff.org",
)
